ERROR - 2023-02-10 00:02:32 --> Error connecting to the database: mysqli_sql_exception: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond in C:\NOVAL\App\mail-tracking-minerba\mail-tracking\starter\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 C:\NOVAL\App\mail-tracking-minerba\mail-tracking\starter\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('mailtrackminerb...', 'n1571149_mailtr...', 'mailtracking202...', 'n1571149_testma...', 3306, '', 0)
#1 C:\NOVAL\App\mail-tracking-minerba\mail-tracking\starter\vendor\codeigniter4\framework\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\NOVAL\App\mail-tracking-minerba\mail-tracking\starter\vendor\codeigniter4\framework\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\NOVAL\App\mail-tracking-minerba\mail-tracking\starter\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1602): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\NOVAL\App\mail-tracking-minerba\mail-tracking\starter\vendor\codeigniter4\framework\system\Model.php(267): CodeIgniter\Database\BaseBuilder->get()
#5 C:\NOVAL\App\mail-tracking-minerba\mail-tracking\starter\vendor\codeigniter4\framework\system\BaseModel.php(656): CodeIgniter\Model->doFirst()
#6 C:\NOVAL\App\mail-tracking-minerba\mail-tracking\starter\app\Models\ModelOtentikasi.php(17): CodeIgniter\BaseModel->first()
#7 C:\NOVAL\App\mail-tracking-minerba\mail-tracking\starter\app\Helpers\jwt_helper.php(22): App\Models\ModelOtentikasi->getEmployee('196410031993031...', '196410031993031...')
#8 C:\NOVAL\App\mail-tracking-minerba\mail-tracking\starter\app\Filters\FilterJwt.php(22): validateJWT('eyJ0eXAiOiJKV1Q...')
#9 C:\NOVAL\App\mail-tracking-minerba\mail-tracking\starter\vendor\codeigniter4\framework\system\Filters\Filters.php(173): App\Filters\FilterJwt->before(Object(CodeIgniter\HTTP\IncomingRequest), NULL)
#10 C:\NOVAL\App\mail-tracking-minerba\mail-tracking\starter\vendor\codeigniter4\framework\system\CodeIgniter.php(473): CodeIgniter\Filters\Filters->run('lookup/detail', 'before')
#11 C:\NOVAL\App\mail-tracking-minerba\mail-tracking\starter\vendor\codeigniter4\framework\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\NOVAL\App\mail-tracking-minerba\mail-tracking\starter\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 C:\NOVAL\App\mail-tracking-minerba\mail-tracking\starter\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('C:\\NOVAL\\App\\ma...')
#14 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond in C:\NOVAL\App\mail-tracking-minerba\mail-tracking\starter\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\NOVAL\App\mail-tracking-minerba\mail-tracking\starter\vendor\codeigniter4\framework\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\NOVAL\App\mail-tracking-minerba\mail-tracking\starter\vendor\codeigniter4\framework\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\NOVAL\App\mail-tracking-minerba\mail-tracking\starter\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1602): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\NOVAL\App\mail-tracking-minerba\mail-tracking\starter\vendor\codeigniter4\framework\system\Model.php(267): CodeIgniter\Database\BaseBuilder->get()
#4 C:\NOVAL\App\mail-tracking-minerba\mail-tracking\starter\vendor\codeigniter4\framework\system\BaseModel.php(656): CodeIgniter\Model->doFirst()
#5 C:\NOVAL\App\mail-tracking-minerba\mail-tracking\starter\app\Models\ModelOtentikasi.php(17): CodeIgniter\BaseModel->first()
#6 C:\NOVAL\App\mail-tracking-minerba\mail-tracking\starter\app\Helpers\jwt_helper.php(22): App\Models\ModelOtentikasi->getEmployee('196410031993031...', '196410031993031...')
#7 C:\NOVAL\App\mail-tracking-minerba\mail-tracking\starter\app\Filters\FilterJwt.php(22): validateJWT('eyJ0eXAiOiJKV1Q...')
#8 C:\NOVAL\App\mail-tracking-minerba\mail-tracking\starter\vendor\codeigniter4\framework\system\Filters\Filters.php(173): App\Filters\FilterJwt->before(Object(CodeIgniter\HTTP\IncomingRequest), NULL)
#9 C:\NOVAL\App\mail-tracking-minerba\mail-tracking\starter\vendor\codeigniter4\framework\system\CodeIgniter.php(473): CodeIgniter\Filters\Filters->run('lookup/detail', 'before')
#10 C:\NOVAL\App\mail-tracking-minerba\mail-tracking\starter\vendor\codeigniter4\framework\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\NOVAL\App\mail-tracking-minerba\mail-tracking\starter\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 C:\NOVAL\App\mail-tracking-minerba\mail-tracking\starter\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('C:\\NOVAL\\App\\ma...')
#13 {main}
CRITICAL - 2023-02-10 00:02:32 --> Unable to connect to the database.
Main connection [MySQLi]: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1602): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `v_access`
WHERE `employeeId` = :employeeId:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Model.php(267): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(656): CodeIgniter\Model->doFirst()
 5 APPPATH\Models\ModelOtentikasi.php(17): CodeIgniter\BaseModel->first()
 6 APPPATH\Helpers\jwt_helper.php(22): App\Models\ModelOtentikasi->getEmployee('196410031993031002', '196410031993031002')
 7 APPPATH\Filters\FilterJwt.php(22): validateJWT('eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJuaXAiOiIxOTY0MTAwMzE5OTMwMzEwMDIiLCJwYXNzd29yZCI6IjE5NjQxMDAzMTk5MzAzMTAwMiIsImlhdCI6MTY3NjAwODk0MiwiZXhwIjoxNjc2MDEyNTQyfQ.r99RFxhQxlvLVdN1iYFP6umB6qLM4QxpZQqiYTEjxXo')
 8 SYSTEMPATH\Filters\Filters.php(173): App\Filters\FilterJwt->before(Object(CodeIgniter\HTTP\IncomingRequest), null)
 9 SYSTEMPATH\CodeIgniter.php(473): CodeIgniter\Filters\Filters->run('lookup/detail', 'before')
10 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
CRITICAL - 2023-02-10 23:16:10 --> Call to undefined method CodeIgniter\Database\MySQLi\Result::first()
in APPPATH\Models\ModelUnknown.php on line 27.
 1 APPPATH\Controllers\Unknown.php(41): App\Models\ModelUnknown->getUnknownById('198412192009021001sdbl16p47txux')
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Unknown->create()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Unknown))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
CRITICAL - 2023-02-10 23:19:26 --> Call to undefined function App\Models\findAll()
in APPPATH\Models\ModelUnknown.php on line 27.
 1 APPPATH\Controllers\Unknown.php(41): App\Models\ModelUnknown->getUnknownById('198412192009021001sdbl16p47txux')
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Unknown->create()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Unknown))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
CRITICAL - 2023-02-10 23:22:44 --> Undefined variable $data
in APPPATH\Models\ModelUnknown.php on line 27.
 1 APPPATH\Models\ModelUnknown.php(27): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $data', 'APPPATH\\Models\\ModelUnknown.php', 27)
 2 APPPATH\Controllers\Unknown.php(41): App\Models\ModelUnknown->getUnknownById('198412192009021001sdb37g0qmka8')
 3 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Unknown->create()
 4 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Unknown))
 5 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
CRITICAL - 2023-02-10 23:23:20 --> Object of class App\Models\ModelUnknown could not be converted to string
in APPPATH\Models\ModelUnknown.php on line 27.
 1 APPPATH\Controllers\Unknown.php(41): App\Models\ModelUnknown->getUnknownById('198412192009021001sdbl16p47txux')
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Unknown->create()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Unknown))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
CRITICAL - 2023-02-10 23:24:26 --> Call to undefined method CodeIgniter\Database\MySQLi\Builder::first()
in APPPATH\Models\ModelUnknown.php on line 27.
 1 APPPATH\Controllers\Unknown.php(41): App\Models\ModelUnknown->getUnknownById('198412192009021001sdbl16p47txux')
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Unknown->create()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Unknown))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
CRITICAL - 2023-02-10 23:25:28 --> Call to undefined method CodeIgniter\Database\MySQLi\Builder::first()
in APPPATH\Models\ModelUnknown.php on line 27.
 1 APPPATH\Controllers\Unknown.php(41): App\Models\ModelUnknown->getUnknownById('198412192009021001sdbl16p47txux')
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Unknown->create()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Unknown))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
CRITICAL - 2023-02-10 23:26:24 --> Call to undefined method CodeIgniter\Database\MySQLi\Builder::first()
in APPPATH\Models\ModelUnknown.php on line 27.
 1 APPPATH\Controllers\Unknown.php(41): App\Models\ModelUnknown->getUnknownById('198412192009021001sdbl16p47txux')
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Unknown->create()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Unknown))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
CRITICAL - 2023-02-10 23:28:53 --> Undefined array key "trackingid"
in APPPATH\Models\ModelUnknown.php on line 26.
 1 APPPATH\Models\ModelUnknown.php(26): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "trackingid"', 'APPPATH\\Models\\ModelUnknown.php', 26)
 2 APPPATH\Controllers\Unknown.php(41): App\Models\ModelUnknown->getUnknownById([...])
 3 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Unknown->create()
 4 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Unknown))
 5 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
CRITICAL - 2023-02-10 23:29:34 --> Attempt to read property "trackingid" on array
in APPPATH\Models\ModelUnknown.php on line 26.
 1 APPPATH\Models\ModelUnknown.php(26): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Attempt to read property "trackingid" on array', 'APPPATH\\Models\\ModelUnknown.php', 26)
 2 APPPATH\Controllers\Unknown.php(41): App\Models\ModelUnknown->getUnknownById([...])
 3 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Unknown->create()
 4 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Unknown))
 5 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
CRITICAL - 2023-02-10 23:29:57 --> Attempt to read property "trackingid" on string
in APPPATH\Models\ModelUnknown.php on line 26.
 1 APPPATH\Models\ModelUnknown.php(26): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Attempt to read property "trackingid" on string', 'APPPATH\\Models\\ModelUnknown.php', 26)
 2 APPPATH\Controllers\Unknown.php(41): App\Models\ModelUnknown->getUnknownById('[{"trackingid":"198412192009021001sdbl16p47txux","unitTo":"DBM.PU","updateDate":"2023-02-11","updateBy":"198412192009021001"}]')
 3 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Unknown->create()
 4 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Unknown))
 5 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
CRITICAL - 2023-02-10 23:30:35 --> Cannot access offset of type string on string
in APPPATH\Models\ModelUnknown.php on line 26.
 1 APPPATH\Controllers\Unknown.php(41): App\Models\ModelUnknown->getUnknownById('[{"trackingid":"198412192009021001sdb9s2pqsyeio","unitTo":"DBM.PU.2","updateDate":"2023-02-11","updateBy":"198412192009021001"}]')
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Unknown->create()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Unknown))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
CRITICAL - 2023-02-10 23:31:39 --> Undefined array key "trackingid"
in APPPATH\Models\ModelUnknown.php on line 26.
 1 APPPATH\Models\ModelUnknown.php(26): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "trackingid"', 'APPPATH\\Models\\ModelUnknown.php', 26)
 2 APPPATH\Controllers\Unknown.php(41): App\Models\ModelUnknown->getUnknownById([...])
 3 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Unknown->create()
 4 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Unknown))
 5 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
CRITICAL - 2023-02-10 23:32:29 --> Cannot use object of type stdClass as array
in APPPATH\Models\ModelUnknown.php on line 26.
 1 APPPATH\Controllers\Unknown.php(41): App\Models\ModelUnknown->getUnknownById([...])
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Unknown->create()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Unknown))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
CRITICAL - 2023-02-10 23:34:14 --> Undefined array key "trackingid"
in APPPATH\Controllers\Unknown.php on line 55.
 1 APPPATH\Controllers\Unknown.php(55): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key "trackingid"', 'APPPATH\\Controllers\\Unknown.php', 55)
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Unknown->create()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Unknown))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
CRITICAL - 2023-02-10 23:34:36 --> Cannot use object of type stdClass as array
in APPPATH\Controllers\Unknown.php on line 55.
 1 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Unknown->create()
 2 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Unknown))
 3 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
CRITICAL - 2023-02-10 23:35:04 --> Cannot use object of type stdClass as array
in APPPATH\Controllers\Unknown.php on line 55.
 1 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Unknown->create()
 2 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Unknown))
 3 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
CRITICAL - 2023-02-10 23:36:10 --> Array to string conversion
in APPPATH\Controllers\Unknown.php on line 37.
 1 APPPATH\Controllers\Unknown.php(37): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Array to string conversion', 'APPPATH\\Controllers\\Unknown.php', 37)
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Unknown->create()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Unknown))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
CRITICAL - 2023-02-10 23:37:34 --> Cannot use object of type stdClass as array
in APPPATH\Controllers\Unknown.php on line 55.
 1 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Unknown->create()
 2 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Unknown))
 3 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
CRITICAL - 2023-02-10 23:39:13 --> Cannot use object of type stdClass as array
in APPPATH\Models\ModelUnknown.php on line 26.
 1 APPPATH\Controllers\Unknown.php(41): App\Models\ModelUnknown->getUnknownById(Object(stdClass))
 2 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Unknown->create()
 3 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Unknown))
 4 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
